# There are many classification algorithms that can be used for different types of datasets and problems. Some commonly used classification algorithms include:

* Logistic Regression
* Naive Bayes
* Decision Tree
* Random Forest
* Support Vector Machines (SVM)
* K-Nearest Neighbors (KNN)
* Neural Networks (NN)
* Gradient Boosting
* AdaBoost
* XGBoost

In [4]:
import pandas as pd
import numpy as np
%matplotlib inline 
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np 
%matplotlib inline
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
from sklearn.metrics import confusion_matrix,recall_score,f1_score
from sklearn.metrics import plot_roc_curve
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from sklearn.metrics import accuracy_score, classification_report

In [5]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Load data
data = pd.read_csv('processed.cleveland.csv')

data['ca'].fillna(data['ca'].mean(),inplace=True )
data['thal'].fillna(data['thal'].mean(),inplace=True )

# Split data into features and target
X = data.drop('target', axis=1)
y = data['target']

# Perform feature selection (e.g. using SelectKBest)
from sklearn.feature_selection import SelectKBest, chi2
X = SelectKBest(chi2, k=5).fit_transform(X, y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Deal with imbalanced data using SMOTE
oversampler = SMOTE()
X_train, y_train = oversampler.fit_resample(X_train, y_train)

# Initialize the model
#model = LogisticRegression()
model = LogisticRegression(penalty='l1', solver='liblinear')
# Perform hyperparameter tuning using GridSearchCV



param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}
grid_search = GridSearchCV(model, param_grid, cv=5)
grid_search.fit(X_train, y_train)
model = grid_search.best_estimator_
#model = RandomForestClassifier()
# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the model's performance
score = model.score(X_test, y_test)
print('Accuracy:', score)
#Print the classification report
report = classification_report(y_test, y_pred)
print(report)


Accuracy: 0.6065573770491803
              precision    recall  f1-score   support

           0       0.90      0.90      0.90        29
           1       0.42      0.42      0.42        12
           2       0.00      0.00      0.00         9
           3       0.30      0.43      0.35         7
           4       0.30      0.75      0.43         4

    accuracy                           0.61        61
   macro avg       0.38      0.50      0.42        61
weighted avg       0.56      0.61      0.58        61



C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Load data
data = pd.read_csv('processed.cleveland.csv')

data['ca'].fillna(data['ca'].mean(),inplace=True )
data['thal'].fillna(data['thal'].mean(),inplace=True )

# Split data into features and target
X = data.drop('target', axis=1)
y = data['target']

# Perform feature selection (e.g. using SelectKBest)
from sklearn.feature_selection import SelectKBest, chi2
X = SelectKBest(chi2, k=5).fit_transform(X, y)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Deal with imbalanced data using SMOTE
oversampler = SMOTE()
X_train, y_train = oversampler.fit_resample(X_train, y_train)

model = RandomForestClassifier()
# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = model.predict(X_test)

# Evaluate the model's performance
score = model.score(X_test, y_test)
print('Accuracy:', score)


Accuracy: 0.5245901639344263


In [9]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# Load the data
data = pd.read_csv('processed.cleveland.csv')

data['ca'].fillna(data['ca'].mean(),inplace=True )
data['thal'].fillna(data['thal'].mean(),inplace=True )

# Split data into features and target
X = data.drop('target', axis=1)
y = data['target']


# Encode the labels as numerical values
le = LabelEncoder()
data['target'] = le.fit_transform(data['target'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)


# Train the KNN model
clf = KNeighborsClassifier( )
clf.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = clf.predict(X_test)

# Decode the numerical labels back to their original categorical values
y_test = le.inverse_transform(y_test)
y_pred = le.inverse_transform(y_pred)

# Evaluate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print the classification report
report = classification_report(y_test, y_pred)
print(report)


Accuracy: 0.44
              precision    recall  f1-score   support

           0       0.55      0.93      0.69        29
           1       0.00      0.00      0.00        12
           2       0.00      0.00      0.00         9
           3       0.00      0.00      0.00         7
           4       0.00      0.00      0.00         4

    accuracy                           0.44        61
   macro avg       0.11      0.19      0.14        61
weighted avg       0.26      0.44      0.33        61



C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are

In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

# Load data
heart_df = pd.read_csv('processed.cleveland.csv')

heart_df['ca'].fillna(data['ca'].mean(),inplace=True )
heart_df['thal'].fillna(data['thal'].mean(),inplace=True )

# Split data into features and target
X =heart_df.drop('target', axis=1)
y =heart_df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [18]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred = knn.predict(X_test_scaled)


C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [19]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print("Accuracy: ", accuracy)
print("Confusion Matrix: \n", conf_matrix)


Accuracy:  0.5737704918032787
Confusion Matrix: 
 [[29  0  0  0  0]
 [ 6  3  3  0  0]
 [ 2  3  2  1  1]
 [ 1  4  1  1  0]
 [ 1  1  1  1  0]]


In [23]:
from sklearn.model_selection import GridSearchCV

knn_params = {'n_neighbors': np.arange(1, 10)}
knn_gs = GridSearchCV(KNeighborsClassifier(), knn_params, cv=5)
knn_gs.fit(X_train_scaled, y_train)

print("Best Parameters: ", knn_gs.best_params_)
print("Best Score: ", knn_gs.best_score_)

y_pred_tuned = knn_gs.predict(X_test_scaled)
accuracy_tuned = accuracy_score(y_test, y_pred_tuned)

print("Tuned Accuracy: ", accuracy_tuned)


Best Parameters:  {'n_neighbors': 6}
Best Score:  0.6198979591836735
Tuned Accuracy:  0.5573770491803278


C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\RANJEET\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `kee